export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const LOGOUT_USERS_REQUEST = 'LOGOUT_USERS_SUCCESS';
export const LOGOUT_USERS_SUCCESS = 'LOGOUT_USERS_SUCCESS';
export const LOGOUT_USERS_FAILED = 'LOGOUT_USERS_FAILED';
