export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const API_USERS_DATA = 'API_USERS_DATA';
export const LOGOUT_USERS = 'LOGOUT_USERS';
